library(shiny)
library(ggplot2)
library(plotly)
require(gapminder)

# Define UI for application 
shinyUI(fluidPage(

    # Application title
    titlePanel("Gapminder: Changes in the health and wealth of nations with time"),

    # Sidebar with a slider input for year
    sidebarLayout(
        sidebarPanel(
            sliderInput(inputId = "year",
                        label = "slide in 5-year steps",
                        min = 1952,
                        max = 2007,
                        step = 5,
                        value = 1957),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            
            selectInput(inputId = "country",
                      label = "Select Country",
                      choices = gapminder$country,
                      selected = 1,
                      ),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
        ),

        # Show a plot of the generated distribution
        mainPanel(
            h4("Global: Life expectancy in years by GDP per capita"),
            br(),
            br(),
            plotOutput("gdplife"),
            br(),
            br(),
            br(),
            br(),
            h4("Country: Percent difference in GDP per capita between 1952 and 2007"),
            textOutput("gdpchange"),
            br(),
            br(),
            plotOutput("country"),
            br(),
            br(),
            br(),
            h4("Country: Difference in life expectancy between 1952 and 2007"),
            textOutput("lifeexpchange"),
            br(),
            br(),
            plotOutput("country2")
            
        )
    )
))
